### ISSUE TITLE
Update fonts and misc styles

### ISSUE THREAD

**Issue by erchaves** [erchaves/syllable-website#12]
Please update fonts per AI design.

![image](https://user-images.githubusercontent.com/302309/54848456-ab68a980-4cb7-11e9-96f8-7c44fbb041ce.png)

Please update portfolio arrow buttons to be circles. This is from an old design that isn't in the new one, but make it like this.
![Screen Shot 2019-03-22 at 3 36 30 PM](https://user-images.githubusercontent.com/302309/54848703-6abd6000-4cb8-11e9-8445-637e7140fe32.png)

**Comment by saracorenzwit** [comment]
https://github.com/erchaves/syllable-website/pull/14
