### ISSUE TITLE
New header design

### ISSUE THREAD

**Issue by erchaves** [erchaves/syllable-website#13]
When page is active, give it one dot (•) on the left. Use a • character. Maybe make it bold if it looks better in the font

![Screen Shot 2019-03-22 at 3 28 40 PM](https://user-images.githubusercontent.com/302309/54848723-7ad53f80-4cb8-11e9-8435-67a90ded4611.png)

Let's try expanding with full dots on hover with a little css transition to see how it looks. Open to ideas here... let's chat about it.
![Screen Shot 2019-03-22 at 3 46 51 PM](https://user-images.githubusercontent.com/302309/54849132-c2a89680-4cb9-11e9-86bc-a0039c8ae0e8.png)
![Screen Shot 2019-03-22 at 3 46 40 PM](https://user-images.githubusercontent.com/302309/54849133-c2a89680-4cb9-11e9-8dff-c3582c535b63.png)
![Screen Shot 2019-03-22 at 3 46 16 PM](https://user-images.githubusercontent.com/302309/54849134-c2a89680-4cb9-11e9-9722-61bdfdd2d498.png)

**Comment by saracorenzwit** [comment]
Should we keep the '/about' path or change to '/studio'?

**Comment by saracorenzwit** [comment]
https://github.com/erchaves/syllable-website/pull/15
